# Site settings
title: 翡翠Android组
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Emerald Education
description: "翡翠教育：产品部Android组信息发布"
baseurl: ""
url: "http://feicuiedu.com"
# twitter_username: SBootstrap
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia
# email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
